trigger:
  - none

pool: 
  name: "lucknow_agent2"
 

stages:
- stage: TerraformStage
  jobs:
  - job: TerraformJob
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV5@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'vinod-app-azure-lucknow'
        backendAzureRmStorageAccountName: 'robinb17storage'
        backendAzureRmContainerName: 'mycontainer'
        backendAzureRmKey: 'vinodkey'

    - task: TerraformTaskV5@5
      inputs:
        provider: 'azurerm'
        command: 'validate'

    - task: TerraformTaskV5@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'vinod-app-azure-lucknow'
