trigger:
  - none  # Manual trigger only

pool: "lucknow_agent2"

variables:
  sys_path: '$(System.DefaultWorkingDirectory)/pra1'

stages:
  - stage: Init_Validate
    displayName: 'Terraform Init & Validate'
    jobs:
      - job: TerraformInitValidate
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: $(sys_path)
              backendServiceArm: 'vinod-app-azure-lucknow'
              backendAzureRmStorageAccountName: 'robinb17storage'
              backendAzureRmContainerName: 'mycontainer'
              backendAzureRmKey: 'vinodkey'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: $(sys_path)

  - stage: Plan
    displayName: 'Terraform Plan'
    dependsOn: Init_Validate
    jobs:
      - job: TerraformPlan
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: $(sys_path)
              environmentServiceNameAzureRM: 'vinod-app-azure-lucknow'

  - stage: Apply
    displayName: 'Terraform Apply'
    dependsOn: Plan
    condition: succeeded()
    jobs:
      - job: TerraformApply
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: $(sys_path)
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: 'vinod-app-azure-lucknow'
