trigger:
  branches:
    include:
      - main
      - feature/*
variables:
  var_path: '$(System.DefaultWorkingDirectory)/infra'
jobs: 
- job:
  displayName: My First Job
  pool: agent5
  steps:
     - task: TerraformInstaller@1
       inputs:
          terraformVersion: 'latest'
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(var_path)'
         backendServiceArm: 'connection_new'
         backendAzureRmStorageAccountName: 'vinodmainstorage'
         backendAzureRmContainerName: 'vinodconatiner'
         backendAzureRmKey: 'vinodkey.tfstate'
      
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'validate'
         workingDirectory: '$(var_path)'
    
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'plan'
         workingDirectory: '$(var_path)'
         environmentServiceNameAzureRM: 'connection_new'

      
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'apply'
         workingDirectory: '$(var_path)'
         commandOptions: '-auto-approve'
         environmentServiceNameAzureRM: 'connection_new'
      
