trigger:
  - none

pool: 
  name: "lucknow_agent5"
 

stages:
- stage: TerraformStage
  jobs:
  - job: TerraformJob
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        commandOptions: 'terraform init -upgrade'
        backendServiceArm: 'vinod-app-azure-lucknow'
        backendAzureRmOverrideSubscriptionID: '4666927b-089e-4cfc-8592-146c2e04657e'
        backendAzureRmStorageAccountName: 'robinb17storage'
        backendAzureRmContainerName: 'mycontainer'
        backendAzureRmKey: 'vinodkey.tfstate'
    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'vinod-app-azure-lucknow'
