trigger: none

pool:
  name: "lucknow_agent2"

variables:
  svc: 'my-webapp-connect'
  config-path: '$(System.DefaultWorkingDirectory)'

parameters:
  - name: init
    type: boolean
    default: false

  - name: validate
    type: boolean
    default: false

  - name: plan
    type: boolean
    default: false

  - name: apply
    type: boolean
    default: false

  - name: environment
    type: string
    default: preprod
    values:
      - dev
      - preprod
      - prod

# '${parameters.environment}}.tfstate' = 'preprod.tfstate'
# -var-file=../resource_group/dev.tfvars
# terraform plan -var-file=dev.tfvars

# '${}' -- variable
# $(config-path)/${{parameters.environment}}.tfvars

steps:
# task 1: terraform ko install marenge
- task: TerraformInstaller@1
  displayName: 'Terraform tool ko install kar rahe hain'
  inputs:
    terraformVersion: 'latest'

# task 2: terraform init
- task: TerraformTask@5
  displayName: 'Terraform init kar do'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'vinod-app-azure-lucknow'
    backendAzureRmStorageAccountName: 'robinb17storage'
    backendAzureRmContainerName: 'mycontainer'
    backendAzureRmKey: 'myterraform.tfstate'
 
- task: TerraformTask@5
  displayName: 'Terraform project ko validate ka rahe hain'
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: 'Terraform ko plan mar dia'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'vinod-app-azure-lucknow'

- task: TerraformTask@5
  displayName: 'Terraform ko apply mar dia'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'vinod-app-azure-lucknow'

 
