name: Terraform Azure Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    name: Terraform Init & Apply
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    

    - name: Azure Login  (OIDC)
      uses: Azure/login@v2.3.0
      with:
        # ClientId of the Azure Service principal created.
        client-id: 53079823-d8aa-4985-91f2-988dea424d31
        # TenantId of the Azure Service principal created.
        tenant-id: ee2f7139-4072-4385-99fc-82bd6f563aa6
        # Azure subscriptionId
        subscription-id: 98b7163f-e961-4b65-98c2-7a6dc2edf5b7
        
            
    - name: Show Azure Account Info
      run: az account show
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      run: terraform init
      working-directory: infra
      
        
    - name: Terraform Plan
      run: |
        terraform plan -no-color -out=tfplan.out
        terraform show -no-color tfplan.out
      working-directory: infra

    - name: Terraform Show (Readable)
      run: terraform show -no-color tfplan.out
      working-directory: infra


    - name: Terraform Apply
      run: |
        terraform apply -auto-approve tfplan.out
        terraform show -no-color tfplan.out
      working-directory: infra
