name: Terraform Azure Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Init & Apply
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug Current Path
      run: |
        Get-Location
        Get-ChildItem

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5  # Use latest version or customize as needed

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init
      working-directory: infra
      
    - name: Print current path
      run: |
        pwd
        ls
        
    - name: Terraform Plan
      run: |
        terraform plan -no-color -out=tfplan.out
        terraform show -no-color tfplan.out
      working-directory: infra

    - name: Print current path
      run: |
        pwd
        ls

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan.out
      working-directory: infra
