name: Terraform Azure Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Init & Apply
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    
        
    
    - name: Debug Current Path
      run: |
        Get-Location
        Get-ChildItem

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5  # Use latest version or customize as needed

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        # ClientId of the Azure Service principal created.
        client-id: 40e54066-731b-48f2-89ab-46a3a97f6e63
        # TenantId of the Azure Service principal created.
        tenant-id: 6959824b-72a3-448d-9d04-fffb6db34d48
        # Azure subscriptionId
        subscription-id: 96a3eaff-d4cf-4222-9fe7-1622ab46f13e

    - name: Login to Azure using credential
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init
      working-directory: infra
      
    - name: Print current path
      run: |
        pwd
        ls
        
    - name: Terraform Plan
      run: |
        terraform plan -no-color -out=tfplan.out
        terraform show -no-color tfplan.out
      working-directory: infra

    - name: Print current path
      run: |
        pwd
        ls

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve tfplan.out
        terraform show -no-color tfplan.out
      working-directory: infra
